variables: !include variables.yaml
global_cuts: !include splits/simple-split.yaml

# for k-folded splits, only required for final trainings of GN2
# global_cuts: !include splits/fold0.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.yonoda.601229.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"
    - "user.yonoda.601230.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.yonoda.800030.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"


lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [bjets, cjets]
    num_jets: 45_000_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [ujets]
    num_jets: 90_000_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [taujets]
    num_jets: 6_250_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [bjets, cjets]
    num_jets: 18_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [ujets]
    num_jets: 36_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [taujets]
    num_jets: 2_500_000
    equal_jets: False


resampling:
  target: cjets
  method: countup
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 25_000_000
  base_dir: /gpfs/fs8001/yonoda/strangelabelling_resampling
  ntuple_dir: /gpfs/fs8001/yonoda/strangelabelling_h5
