variables: !include /home/yonoda/upp-adding-new-labelling/umami-preprocessing/upp/configs/variables.yaml
global_cuts: !include /home/yonoda/upp-adding-new-labelling/umami-preprocessing/upp/configs/splits/simple-split.yaml

# for k-folded splits, only required for final trainings of GN2
# global_cuts: !include splits/fold0.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.yonoda.601229.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"
    - "user.yonoda.601230.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.yonoda.800030.e8514_s4162_r14622_p6215.tdd.EMPFlow.25_2_20.24-08-21_strangejet.labelling_output.h5/*.h5"


lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [hadronghostdecaymodebjets, hadronghostdecaymodecjets]
    num_jets: 4_500_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [hadronghostdecaymodesjets]
    num_jets: 1_800_000
    equal_jets: False
  
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [hadronghostdecaymodelightjets]
    num_jets: 7_200_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [hadronghostdecaymodetaujets]
    num_jets: 625_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [hadronghostdecaymodebjets, hadronghostdecaymodecjets]
    num_jets: 1_800_000
    equal_jets: False 

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [hadronghostdecaymodesjets]
    num_jets: 720_000
    equal_jets: False
  
  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [hadronghostdecaymodelightjets]
    num_jets: 2_880_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [hadronghostdecaymodetaujets]
    num_jets: 250_000
    equal_jets: False


resampling:
  target: hadronghostdecaymodecjets
  method: countup
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 100_000
  num_jets_estimate: 2_500_000
  base_dir: /gpfs/fs8001/yonoda/strangelabelling_resampling_decaymode
  ntuple_dir: /gpfs/fs8001/yonoda/strangelabelling_h5
